const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;
const PAGE_MARGIN = 42;
const MAX_TEXT_WIDTH = 74;

function setCors(res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, HEAD, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.setHeader('Cache-Control', 'no-store');
}

function decodeBase64Url(value) {
  const normalized = String(value || '').replace(/-/g, '+').replace(/_/g, '/');
  const padding = normalized.length % 4 === 0 ? '' : '='.repeat(4 - (normalized.length % 4));
  return Buffer.from(normalized + padding, 'base64').toString('utf8');
}

function sanitizePdfText(value) {
  return String(value ?? '')
    .normalize('NFKD')
    .replace(/[^\x20-\x7E]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function pdfEscape(value) {
  return sanitizePdfText(value)
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)');
}

function wrapText(value, maxLength = MAX_TEXT_WIDTH) {
  const text = sanitizePdfText(value);
  if (!text) return ['-'];
  const words = text.split(/\s+/);
  const lines = [];
  let current = '';
  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (next.length <= maxLength) {
      current = next;
      continue;
    }
    if (current) lines.push(current);
    if (word.length <= maxLength) {
      current = word;
      continue;
    }
    let rest = word;
    while (rest.length > maxLength) {
      lines.push(rest.slice(0, maxLength - 1) + '-');
      rest = rest.slice(maxLength - 1);
    }
    current = rest;
  }
  if (current) lines.push(current);
  return lines.length ? lines : ['-'];
}

function createInvoiceLines(data) {
  const lines = [];
  let y = PAGE_HEIGHT - 52;

  const pushLine = (text, options = {}) => {
    const line = {
      text,
      x: options.x ?? PAGE_MARGIN,
      y,
      font: options.font || 'F1',
      size: options.size || 11,
      color: options.color || [23, 32, 51],
    };
    lines.push(line);
    y -= options.gap || 16;
    if (y < 70) {
      lines.push({ pageBreak: true });
      y = PAGE_HEIGHT - 52;
    }
  };

  const pushSpacer = (gap = 8) => {
    y -= gap;
  };

  pushLine('KRISCENT TECHNO HUB', { font: 'F2', size: 12, color: [16, 26, 58], gap: 20 });
  pushLine('Project Invoice', { font: 'F2', size: 24, color: [16, 26, 58], gap: 26 });
  pushLine(`Invoice ID: ${data.invoiceId}`, { font: 'F2', size: 12, gap: 18 });
  pushLine(`Generated: ${data.generatedAt}`, { size: 10, color: [100, 116, 139], gap: 22 });

  const fields = [
    ['Client', data.companyName],
    ['Owner', data.ownerName],
    ['Client Email', data.clientEmail],
    ['Client Phone', data.clientPhone],
    ['Service', data.serviceType],
    ['Invoice Status', data.invoiceStatus],
    ['Assigned To', data.assignedTo],
    ['Total Amount (USD)', `$${Number(data.totalAmount || 0).toLocaleString('en-US')}`],
    ['Paid Amount (USD)', `$${Number(data.paidAmount || 0).toLocaleString('en-US')}`],
    ['Balance Due (USD)', `$${Number(data.dueAmount || 0).toLocaleString('en-US')}`],
    ['Due Date', data.invoiceDueDate],
  ];

  fields.forEach(([label, value]) => {
    pushLine(`${label}: ${value || '-'}`, { gap: 18 });
  });

  pushSpacer(8);
  pushLine('Scope Notes', { font: 'F2', size: 13, gap: 18 });
  wrapText(data.notes || 'No scope notes added yet.', 82).forEach((line) => {
    pushLine(line, { gap: 16 });
  });

  pushSpacer(8);
  pushLine('This PDF was generated by the Kriscent dashboard.', {
    size: 10,
    color: [100, 116, 139],
    gap: 14,
  });

  return lines;
}

function buildPdf(data) {
  const lineSets = createInvoiceLines(data);
  const pages = [];
  let currentPage = [];

  lineSets.forEach((line) => {
    if (line.pageBreak) {
      if (currentPage.length) pages.push(currentPage);
      currentPage = [];
      return;
    }
    currentPage.push(line);
  });
  if (currentPage.length) pages.push(currentPage);
  if (!pages.length) pages.push([]);

  const objects = [];
  objects[1] = '<< /Type /Catalog /Pages 2 0 R >>';
  objects[3] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';
  objects[4] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>';

  const pageRefs = [];
  let objectIndex = 5;

  pages.forEach((pageLines) => {
    const pageObjectIndex = objectIndex++;
    const contentObjectIndex = objectIndex++;
    pageRefs.push(`${pageObjectIndex} 0 R`);

    const stream = pageLines.map((line) => {
      const [r, g, b] = line.color;
      return [
        'BT',
        `/${line.font} ${line.size} Tf`,
        `${(r / 255).toFixed(3)} ${(g / 255).toFixed(3)} ${(b / 255).toFixed(3)} rg`,
        `1 0 0 1 ${line.x.toFixed(2)} ${line.y.toFixed(2)} Tm`,
        `(${pdfEscape(line.text)}) Tj`,
        'ET',
      ].join('\n');
    }).join('\n');

    objects[pageObjectIndex] =
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH.toFixed(2)} ${PAGE_HEIGHT.toFixed(2)}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentObjectIndex} 0 R >>`;
    objects[contentObjectIndex] = `<< /Length ${Buffer.byteLength(stream, 'utf8')} >>\nstream\n${stream}\nendstream`;
  });

  objects[2] = `<< /Type /Pages /Count ${pages.length} /Kids [${pageRefs.join(' ')}] >>`;

  let pdf = '%PDF-1.4\n';
  const offsets = [0];

  for (let i = 1; i < objects.length; i += 1) {
    const body = objects[i];
    if (!body) continue;
    offsets[i] = Buffer.byteLength(pdf, 'utf8');
    pdf += `${i} 0 obj\n${body}\nendobj\n`;
  }

  const xrefOffset = Buffer.byteLength(pdf, 'utf8');
  pdf += `xref\n0 ${objects.length}\n`;
  pdf += '0000000000 65535 f \n';
  for (let i = 1; i < objects.length; i += 1) {
    pdf += `${String(offsets[i] || 0).padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, 'utf8');
}

module.exports = async function handler(req, res) {
  setCors(res);

  if (req.method === 'OPTIONS') {
    return res.status(204).end();
  }

  if (!['GET', 'HEAD'].includes(req.method || 'GET')) {
    return res.status(405).json({ ok: false, error: 'Method not allowed' });
  }

  try {
    const rawData = req.query?.data;
    if (!rawData) {
      return res.status(400).json({ ok: false, error: 'Missing invoice data' });
    }

    const parsed = JSON.parse(decodeBase64Url(rawData));
    const invoiceData = {
      invoiceId: sanitizePdfText(parsed.invoiceId || 'INV-DRAFT'),
      companyName: sanitizePdfText(parsed.companyName || 'Client'),
      ownerName: sanitizePdfText(parsed.ownerName || ''),
      clientEmail: sanitizePdfText(parsed.clientEmail || ''),
      clientPhone: sanitizePdfText(parsed.clientPhone || ''),
      serviceType: sanitizePdfText(parsed.serviceType || ''),
      invoiceStatus: sanitizePdfText(parsed.invoiceStatus || 'Draft'),
      assignedTo: sanitizePdfText(parsed.assignedTo || ''),
      totalAmount: Number(parsed.totalAmount || 0),
      paidAmount: Number(parsed.paidAmount || 0),
      dueAmount: Number(parsed.dueAmount || 0),
      invoiceDueDate: sanitizePdfText(parsed.invoiceDueDate || ''),
      notes: sanitizePdfText(parsed.notes || ''),
      generatedAt: sanitizePdfText(parsed.generatedAt || new Date().toISOString()),
    };

    const pdfBuffer = buildPdf(invoiceData);
    const safeFileName = sanitizePdfText(invoiceData.invoiceId || 'invoice').replace(/[^a-zA-Z0-9._-]+/g, '-');
    const disposition = String(req.query?.download || '') === '1' ? 'attachment' : 'inline';

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Length', String(pdfBuffer.length));
    res.setHeader('Content-Disposition', `${disposition}; filename="${safeFileName || 'invoice'}.pdf"`);

    if (req.method === 'HEAD') {
      return res.status(200).end();
    }

    return res.status(200).send(pdfBuffer);
  } catch (error) {
    return res.status(400).json({
      ok: false,
      error: error instanceof Error ? error.message : 'Invalid invoice payload',
    });
  }
};
